resource "local_file" "env_file" {
  content = <<EOF
# Auto-generated by Terraform
SCW_ACCESS_KEY=${scaleway_iam_api_key.ghost_s3_key.access_key}
SCW_SECRET_KEY=${scaleway_iam_api_key.ghost_s3_key.secret_key}
SCW_REGION=${var.region}
SCW_BUCKET_NAME=${scaleway_object_bucket.content.name}
SCW_DB_HOST=${scaleway_rdb_instance.main.private_network[0].ip}
SCW_DB_PORT=${scaleway_rdb_instance.main.private_network[0].port}
SCW_DB_USER=${scaleway_rdb_user.ghost.name}
SCW_DB_PASSWORD=${local.db_app_password}
SCW_DB_NAME=${scaleway_rdb_database.ghost.name}
EOF
  filename = "${path.module}/../.env"
  file_permission = "0600"
}
